version: '3.8'

services:
  # --- Base de Datos ---
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taskmaster_db
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  # --- Microservicios (Exponemos puertos para pruebas directas) ---
  service-auth:
    build: ./apps/service-auth
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://admin:password123@database:5432/taskmaster_db
      PORT: 3001
    networks:
      - app-network
    depends_on:
      - database

  service-core:
    build: ./apps/service-core
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgres://admin:password123@database:5432/taskmaster_db
      PORT: 3002
    networks:
      - app-network
    depends_on:
      - database

  service-dashboard:
    build: ./apps/service-dashboard
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgres://admin:password123@database:5432/taskmaster_db
      PORT: 3003
    networks:
      - app-network
    depends_on:
      - database

  # --- Frontend (CON INYECCIÓN DE VARIABLES) ---
  frontend:
    build:
      context: ./apps/frontend
      # PASAMOS LAS IPs COMO ARGUMENTOS DE CONSTRUCCIÓN
      args:
        - VITE_AUTH_URL=http://100.28.113.132:3001
        - VITE_CORE_URL=http://3.94.232.24:3002
        - VITE_DASHBOARD_URL=http://34.204.212.17:3003
    ports:
      - "80:3000"
    networks:
      - app-network

  # --- API Gateway (Nginx) ---
  gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./infra/docker/local/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - service-auth
      - service-core
      - service-dashboard
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: